export const publisherActionTypes = {
    CREATE_PUBLISHER : "CREATE_PUBLISHER",

    GET_ALL_PUBLISHERS : "GET_ALL_PUBLISHERS",
    GET_ALL_PUBLISHERS_SUCCESS: "GET_ALL_PUBLISHERS_SUCCESS",
    GET_ALL_PUBLISHERS_ERROR: "GET_ALL_PUBLISHERS_ERROR",

    GET_PUBLISHER_DETAILS : "GET_PUBLISHER_DETAILS",
    GET_PUBLISHER_DETAILS_SUCCESS: "GET_PUBLISHER_DETAILS_SUCCESS",
    GET_PUBLISHER_DETAILS_ERROR: "GET_PUBLISHER_DETAILS_ERROR",

    CLEAR_PUBLISHER_DETAILS : "CLEAR_PUBLISHER_DETAILS" 
}