export const widgetActions = {
  //WIDGET
  GET_WIDGET: "GET_WIDGET",
  GET_WIDGET_SUCCESS: "GET_WIDGET_SUCCESS",
  GET_WIDGET_ERROR: "GET_WIDGET_ERROR",
  GET_WIDGET_RESET_ERROR: "GET_WIDGET_RESET_ERROR",
};
